cv:
  style: davewhipp

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: "syntax"

plugins:
  - jekyll-minifier

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      author: "Alessandro Lorenzi"
      layout: "post"
      fediverse_creator: "@alorenzi@livellosegreto.it"