#!/bin/bash

git add --all
find media -name '*.jpg' | xargs git-lfs track
git add --all

git commit -av

docker run --rm \
  --volume="$PWD:/srv/jekyll:z" \
  -u 0:1000 \
  -p 4000:4000 \
  -it jekyll/jekyll \
  jekyll build

rsync -av _site/ home:/srv/alorenzi_eu/


